/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package App;

import static App.Utils.NombreGrado;
import static App.Utils.TituloGrado;
import static App.Utils.ImagenesCarrusel;
import java.awt.Dimension;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Busid
 */
public class Game1 extends javax.swing.JPanel {

    /**
     * Creates new form Game1
     */
    List<String> rutasImagenesCarrusel;

    JLabel[] puntos;

    int indice = 0;
    int indicePunto = 0;

    Main parent;

    public Game1(int index) {
        initComponents();
        rutasImagenesCarrusel = ImagenesCarrusel(index);
        this.puntos = new JLabel[]{puntoVacio0, puntoVacio1, puntoVacio2, puntoVacio3, puntoVacio4};
        ImageIcon imagenActual = (ImageIcon) carrusellmg.getIcon();
        SetImageLabel(puntoVacio0, "src/Images/InterfazGame/PuntoCarruselFilled.png", new Dimension(16, 17));
        SetImageLabel(carrusellmg, rutasImagenesCarrusel.get(indice), new Dimension(891, 525));
        titulo.setText(TituloGrado(index));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        comenzar = new javax.swing.JButton();
        carruselBox = new javax.swing.JPanel();
        flechaIz = new javax.swing.JButton();
        flechaDe = new javax.swing.JButton();
        carrusellmg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        puntoVacio4 = new javax.swing.JLabel();
        puntoVacio0 = new javax.swing.JLabel();
        puntoVacio2 = new javax.swing.JLabel();
        puntoVacio3 = new javax.swing.JLabel();
        puntoVacio1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 255));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1420, 800));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/Barrita aislada descripción.png"))); // NOI18N
        titulo.setText("Embarque y desembarque en helicóptero");

        comenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/Comenzar.png"))); // NOI18N
        comenzar.setBorderPainted(false);
        comenzar.setContentAreaFilled(false);
        comenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comenzar.setFocusPainted(false);
        comenzar.setFocusable(false);
        comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarActionPerformed(evt);
            }
        });

        carruselBox.setOpaque(false);
        carruselBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flechaIz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/Flecha izquierda.png"))); // NOI18N
        flechaIz.setContentAreaFilled(false);
        flechaIz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flechaIz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flechaIzActionPerformed(evt);
            }
        });
        carruselBox.add(flechaIz, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        flechaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/Flecha derecha.png"))); // NOI18N
        flechaDe.setBorderPainted(false);
        flechaDe.setContentAreaFilled(false);
        flechaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flechaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flechaDeActionPerformed(evt);
            }
        });
        carruselBox.add(flechaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 240, -1, -1));

        carrusellmg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/Miniaturas/Helicoptero/Helicoptero0.png"))); // NOI18N
        carruselBox.add(carrusellmg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 891, 511));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/Cuadrado fondo enfocado.png"))); // NOI18N
        carruselBox.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 770, 430));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/Cuadrado fondo enfocado.png"))); // NOI18N
        carruselBox.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 560, 450));

        puntoVacio4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/PuntoCarruselEmpty.png"))); // NOI18N
        carruselBox.add(puntoVacio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, -1));

        puntoVacio0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/PuntoCarruselEmpty.png"))); // NOI18N
        carruselBox.add(puntoVacio0, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, -1, -1));

        puntoVacio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/PuntoCarruselEmpty.png"))); // NOI18N
        carruselBox.add(puntoVacio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, -1, -1));

        puntoVacio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/PuntoCarruselEmpty.png"))); // NOI18N
        carruselBox.add(puntoVacio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, -1, -1));

        puntoVacio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/PuntoCarruselEmpty.png"))); // NOI18N
        carruselBox.add(puntoVacio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(comenzar)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(carruselBox, javax.swing.GroupLayout.PREFERRED_SIZE, 1216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(carruselBox, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 134, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comenzar))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarActionPerformed
    }//GEN-LAST:event_comenzarActionPerformed

    private void flechaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flechaDeActionPerformed
        indice = (indice + 1) % rutasImagenesCarrusel.size();
        SetImageLabel(carrusellmg, rutasImagenesCarrusel.get(indice), new Dimension(891, 525));
        SetImageLabel(puntos[indice], "src/Images/InterfazGame/PuntoCarruselFilled.png", new Dimension(16, 17));
        if (indicePunto >= 0 && indicePunto < puntos.length) {
            // Actualiza la imagen del punto anterior
            SetImageLabel(puntos[indicePunto], "src/Images/InterfazGame/PuntoCarruselEmpty.png", new Dimension(16, 17));
        }
        indicePunto = indice;
    }//GEN-LAST:event_flechaDeActionPerformed

    private void flechaIzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flechaIzActionPerformed
        indice = (indice - 1 + rutasImagenesCarrusel.size()) % rutasImagenesCarrusel.size();
        SetImageLabel(carrusellmg, rutasImagenesCarrusel.get(indice), new Dimension(891, 525));
        SetImageLabel(puntos[indice], "src/Images/InterfazGame/PuntoCarruselFilled.png", new Dimension(16, 17));
        if (indicePunto >= 0 && indicePunto < puntos.length) {
            // Actualiza la imagen del punto anterior
            SetImageLabel(puntos[indicePunto], "src/Images/InterfazGame/PuntoCarruselEmpty.png", new Dimension(16, 17));
        }
        indicePunto = indice;
    }//GEN-LAST:event_flechaIzActionPerformed

    private void SetImageLabel(JLabel labelName, String root, Dimension dimension) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(
                        dimension.width,
                        dimension.height,
                        Image.SCALE_DEFAULT
                )
        );
        labelName.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel carruselBox;
    private javax.swing.JLabel carrusellmg;
    private javax.swing.JButton comenzar;
    private javax.swing.JButton flechaDe;
    private javax.swing.JButton flechaIz;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel puntoVacio0;
    private javax.swing.JLabel puntoVacio1;
    private javax.swing.JLabel puntoVacio2;
    private javax.swing.JLabel puntoVacio3;
    private javax.swing.JLabel puntoVacio4;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
