/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package App;

import static App.Utils.NombreGrado;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Busid
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    Main parent;

    public Home(Main _parent, int index) {
        initComponents();
        parent = _parent;
        parent.indiceGrado = index;
        parent.indiceJuego = index;
        this.setOpaque(false);
        gradoNombre.setText(NombreGrado(index));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simulador3 = new javax.swing.JButton();
        simulador1 = new javax.swing.JButton();
        simulador4 = new javax.swing.JButton();
        simulador6 = new javax.swing.JButton();
        simulador2 = new javax.swing.JButton();
        simulador5 = new javax.swing.JButton();
        gradoNombre = new javax.swing.JLabel();

        simulador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HomeButton2.png"))); // NOI18N
        simulador3.setContentAreaFilled(false);
        simulador3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simulador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulador3ActionPerformed(evt);
            }
        });

        simulador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HomeButton0.png"))); // NOI18N
        simulador1.setContentAreaFilled(false);
        simulador1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simulador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulador1ActionPerformed(evt);
            }
        });

        simulador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HomeButton5.png"))); // NOI18N
        simulador4.setContentAreaFilled(false);
        simulador4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simulador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulador4ActionPerformed(evt);
            }
        });

        simulador6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HomeButton3.png"))); // NOI18N
        simulador6.setContentAreaFilled(false);
        simulador6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simulador6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulador6ActionPerformed(evt);
            }
        });

        simulador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HomeButton1.png"))); // NOI18N
        simulador2.setContentAreaFilled(false);
        simulador2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simulador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulador2ActionPerformed(evt);
            }
        });

        simulador5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HomeButton4.png"))); // NOI18N
        simulador5.setContentAreaFilled(false);
        simulador5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simulador5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulador5ActionPerformed(evt);
            }
        });

        gradoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gradoNombre.setForeground(new java.awt.Color(255, 255, 255));
        gradoNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfazGame/Barrita aislada descripción.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simulador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simulador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(simulador2)
                    .addComponent(simulador5))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simulador3)
                    .addComponent(simulador6))
                .addGap(171, 171, 171))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(simulador1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simulador3)
                            .addComponent(simulador2))
                        .addGap(51, 51, 51)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simulador6)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(simulador5)
                            .addComponent(simulador4))
                        .addGap(85, 85, 85))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void simulador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulador1ActionPerformed
        parent.ShowPanel(new Game1(0));
    }//GEN-LAST:event_simulador1ActionPerformed

    private void simulador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulador2ActionPerformed
        parent.ShowPanel(new Game1(1));
    }//GEN-LAST:event_simulador2ActionPerformed

    private void simulador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulador3ActionPerformed
        parent.ShowPanel(new Game1(2));
    }//GEN-LAST:event_simulador3ActionPerformed

    private void simulador5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulador5ActionPerformed
        parent.ShowPanel(new Game1(4));
    }//GEN-LAST:event_simulador5ActionPerformed

    private void simulador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulador4ActionPerformed
        parent.ShowPanel(new Game1(5));
    }//GEN-LAST:event_simulador4ActionPerformed

    private void simulador6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulador6ActionPerformed
        parent.ShowPanel(new Game1(3));
    }//GEN-LAST:event_simulador6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel gradoNombre;
    private javax.swing.JButton simulador1;
    private javax.swing.JButton simulador2;
    private javax.swing.JButton simulador3;
    private javax.swing.JButton simulador4;
    private javax.swing.JButton simulador5;
    private javax.swing.JButton simulador6;
    // End of variables declaration//GEN-END:variables
}
