/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import java.awt.BorderLayout;
import java.awt.Button;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Busid
 */
public class Main extends javax.swing.JFrame {

    int indiceGrado;
    int indiceJuego;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Home h = new Home(this, 0);
        ShowPanel(h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        iconos = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        homeBtn1 = new javax.swing.JButton();
        homeBtn2 = new javax.swing.JButton();
        homeBtn3 = new javax.swing.JButton();
        homeBtn4 = new javax.swing.JButton();
        homeBtn5 = new javax.swing.JButton();
        homeBtn6 = new javax.swing.JButton();
        homeBtn7 = new javax.swing.JButton();
        homeBtn8 = new javax.swing.JButton();
        homeBtn9 = new javax.swing.JButton();
        homeBtn10 = new javax.swing.JButton();
        homeBtn11 = new javax.swing.JButton();
        homeBtn12 = new javax.swing.JButton();
        homeBtn13 = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);

        jPanel3.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconos.setOpaque(false);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton6.png"))); // NOI18N
        homeBtn.setContentAreaFilled(false);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        homeBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton2.png"))); // NOI18N
        homeBtn1.setContentAreaFilled(false);
        homeBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn1ActionPerformed(evt);
            }
        });

        homeBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton1.png"))); // NOI18N
        homeBtn2.setContentAreaFilled(false);
        homeBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn2ActionPerformed(evt);
            }
        });

        homeBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton7.png"))); // NOI18N
        homeBtn3.setContentAreaFilled(false);
        homeBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn3ActionPerformed(evt);
            }
        });

        homeBtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton8.png"))); // NOI18N
        homeBtn4.setContentAreaFilled(false);
        homeBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn4ActionPerformed(evt);
            }
        });

        homeBtn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton4.png"))); // NOI18N
        homeBtn5.setContentAreaFilled(false);
        homeBtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn5ActionPerformed(evt);
            }
        });

        homeBtn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton5.png"))); // NOI18N
        homeBtn6.setContentAreaFilled(false);
        homeBtn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn6ActionPerformed(evt);
            }
        });

        homeBtn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton9.png"))); // NOI18N
        homeBtn7.setContentAreaFilled(false);
        homeBtn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn7ActionPerformed(evt);
            }
        });

        homeBtn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton10.png"))); // NOI18N
        homeBtn8.setContentAreaFilled(false);
        homeBtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn8ActionPerformed(evt);
            }
        });

        homeBtn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton11.png"))); // NOI18N
        homeBtn9.setContentAreaFilled(false);
        homeBtn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn9ActionPerformed(evt);
            }
        });

        homeBtn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton3.png"))); // NOI18N
        homeBtn10.setContentAreaFilled(false);
        homeBtn10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn10ActionPerformed(evt);
            }
        });

        homeBtn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton12.png"))); // NOI18N
        homeBtn11.setContentAreaFilled(false);
        homeBtn11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn11ActionPerformed(evt);
            }
        });

        homeBtn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton0.png"))); // NOI18N
        homeBtn12.setContentAreaFilled(false);
        homeBtn12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn12ActionPerformed(evt);
            }
        });

        homeBtn13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LauncherButton13.png"))); // NOI18N
        homeBtn13.setContentAreaFilled(false);
        homeBtn13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout iconosLayout = new javax.swing.GroupLayout(iconos);
        iconos.setLayout(iconosLayout);
        iconosLayout.setHorizontalGroup(
            iconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iconosLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(homeBtn11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        iconosLayout.setVerticalGroup(
            iconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeBtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeBtn13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeBtn12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeBtn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeBtn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(iconosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(iconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeBtn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeBtn7, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(homeBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(homeBtn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeBtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeBtn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(iconos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 1550, 130));

        content.setOpaque(false);
        content.setPreferredSize(new java.awt.Dimension(1400, 700));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel3.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 1420, 800));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FondoBase.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        Home h = new Home(this, 0);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void homeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn1ActionPerformed
        Home h = new Home(this, 1);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn1ActionPerformed

    private void homeBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn3ActionPerformed
        Home h = new Home(this, 3);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn3ActionPerformed

    private void homeBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn4ActionPerformed
        Home h = new Home(this, 4);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn4ActionPerformed

    private void homeBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn5ActionPerformed
        Home h = new Home(this, 5);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn5ActionPerformed

    private void homeBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn6ActionPerformed
        Home h = new Home(this, 6);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn6ActionPerformed

    private void homeBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn7ActionPerformed
        Home h = new Home(this, 7);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn7ActionPerformed

    private void homeBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn8ActionPerformed
        Home h = new Home(this, 8);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn8ActionPerformed

    private void homeBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn9ActionPerformed
        Home h = new Home(this, 9);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn9ActionPerformed

    private void homeBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn10ActionPerformed
        Home h = new Home(this, 10);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn10ActionPerformed

    private void homeBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn12ActionPerformed
        Home h = new Home(this, 12);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn12ActionPerformed

    private void homeBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn11ActionPerformed
        Home h = new Home(this, 11);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn11ActionPerformed

    private void homeBtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn13ActionPerformed
        Home h = new Home(this, 13);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn13ActionPerformed

    private void homeBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn2ActionPerformed
        Home h = new Home(this, 2);
        ShowPanel(h);
    }//GEN-LAST:event_homeBtn2ActionPerformed

    public void ShowPanel(JPanel p) {
        p.setSize(1420, 800);
        p.setLocation(0, 0);

        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel content;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton homeBtn1;
    private javax.swing.JButton homeBtn10;
    private javax.swing.JButton homeBtn11;
    private javax.swing.JButton homeBtn12;
    private javax.swing.JButton homeBtn13;
    private javax.swing.JButton homeBtn2;
    private javax.swing.JButton homeBtn3;
    private javax.swing.JButton homeBtn4;
    private javax.swing.JButton homeBtn5;
    private javax.swing.JButton homeBtn6;
    private javax.swing.JButton homeBtn7;
    private javax.swing.JButton homeBtn8;
    private javax.swing.JButton homeBtn9;
    private javax.swing.JPanel iconos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
